defaults_:                            ${env:CO3_PATH}/co3-configurations/test/gabe/playback_defaults.yaml

playbacks:
  ddpg_parabola_test:
    misc:
      csv_path:                         null
      generate_csv:                     False
      leave_progress_bar:               True
      log_interval:                     2500
      log_level:                        INFO 
      seed:                             7
      record_state:                     False
    agent:
      agent:                            custom_ddpg_agent # ddpg.ddpg_agent # 
      action_noise:
        type:                           OrnsteinUhlenbeck 
        sigma:                          0.02
      batch_size:                       640
      buffer_size:                      640
      gamma:                            0.99 # Bellman discount factor
      gradient_clipping:
          max_norm:                     1.0
          norm_type:                    2.0
      purge_network:                    True
      network:                          networks/ddpg_parabola_test_running
      training:                         True
      training_interval:                640 # Number of steps between trainings of the network
      target_update_interval:           1 # Number of trainings between updating the target
      episodes:                         50000 # 2650134
      torch_models:
        Actor:
          hidden_dims:                  [120, 84]
          activations:                  [nn.ReLU]
        Critic:
          hidden_dims:                  [120, 84]
          activations:                  [nn.ReLU]
      actor_lr:                         3e-5
      critic_lr:                        0.0001
      tau:                              0.001
      policy_noise:                     0.02
      noise_clip:                       0.5
      exploration:                      100

    env_config:
      env_name:                         sentient_gym:SellOrderbookDataFrameEnv-v0
      is_buy:                           False
      ql:                               0.2
      datasets:                         [datasets/evaluate/small_sell_ob_training_log.json]
      precision:                        8
      action_space_low:                 0.0
      action_space_high:                1
      reward_offset:                    1.0
      randomize_dataset_reads:          False
      pdf:
        name:                           pdf-ddpg
        market:                         btc-eth
        start_window:                   90 # days
        start_range:                    2018-01-15T12:30:00
        end_range:                      2019-07-15T13:00:00
        age_limit:                      60 # days, can be decimal; e.g. 0.25 = 6 hrs
        bins:                           auto
        graph:                          True
        envId:                            0
        exchange:                         bittrex

    child_process:
      launch_delay:                     0
      launch_interval:                  1000000
      env_config:
        randomize_dataset_reads:        False
        datasets:                       [datasets/evaluate/small_sell_ob_test_log.json]
      misc:
        csv_path:                       rewards/ddpg/log_test
        generate_csv:                   True
        log_interval:                   2500
      agent:
        episodes:                       20000
