defaults_:                              /shared/co3/co3-configurations/test/gabe/playback_defaults.yaml

console: logging

playbacks:
  test_playback:
    misc:
      csv_path:                         null
      generate_csv:                     False
      leave_progress_bar:               True
      log_interval:                     2500
      log_level:                        INFO 
      seed:                             7
      record_state:                     False
      market:                           btc-eth
    agent:
      # agent:                            parabola_actor_enabled_1
      agent:                            test_agent
      # agent:                            ddpg.ddpg_agent
      # agent:                            td3.td3_agent
      # agent:                            sac.sac_agent
      alpha:                            0.2
      automatic_entropy_tuning:         True
      batch_size:                       64
      buffer_size:                      1000
      gamma:                            0.99 # Bellman discount factor
      gradient_clipping:
          max_norm:                     1.0
          norm_type:                    2.0
      purge_network:                    True
      network:                          networks/test_config
      training:                         True
      training_interval:                50 # Number of steps between trainings of the network
      target_update_interval:           2 # Number of trainings between updating the target

      episodes:                         883351
      torch_models:
        Actor:
          name:                         LayerNorm
          hidden_dims:                  [400, 200, 150]
          activations:                  [nn.ReLU]
        Critic:
          name:                         LayerNorm2
          hidden_dims:                  [250, 200, 150]
          activations:                  [nn.ReLU]
      actor_lr:                         0.0003
      critic_lr:                        0.0003
      tau:                              0.001
      policy_noise:                     0.02
      noise_clip:                       0.5
      exploration:                      100

    env_config:
      env_name:                         sentient_gym:SellOrderbookDataFrameEnv-v0
      is_buy:                           False
      ql:                               0.2
      datasets:                         [/datasets/small_sell_ob_training_log.json]
      precision:                        8
      action_space_low:                 0.02
      action_space_high:                0.98
      get_reward:                       get_reward_parabola
      reward_offset:                    1.0
      randomize_dataset_reads:          False
      pdf:
        name:                           pdf-ddpg
        market:                         btc-eth
        start_window:                   90 # days
        start_range:                    2018-01-15T12:30:00
        end_range:                      2019-07-15T13:00:00
        age_limit:                      360 # days, can be decimal; e.g. 0.25 = 6 hrs
        bins:                           auto
        graph:                          True
        envId:                          0
        exchange:                       bittrex
      

    child_process:
      launch_delay:                     20000
      launch_interval:                  20000
      # launch_delay:                     294450
      # launch_interval:                  294450
      env_config:
        randomize_dataset_reads:        False
        datasets:                       [/datasets/small_sell_ob_test_log.json]
      misc:
        csv_path:                       null
        generate_csv:                   False
        log_interval:                   2500
      agent:
        episodes:                       20000
        batch_size:                     20000
        buffer_size:                    20000
